name: Build Caddy with new version

on:
  release:
    types: [publish]

permissions:
  actions: write
  checks: write
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and Push Docker Image to GitHub Container Registry
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}  -t ghcr.io/${{ github.repository }}:latest --push ./caddy

      - name: Update docker-compose file with correct image
        run: |
          sed -i 's|\(ghcr\.io\/${{ github.repository }}:\)\([^latest].*\)|\1${{ github.event.release.tag_name }}|g' ./README.md

      - name: Commit README change with new version
        uses: EndBug/add-and-commit@v9
        with:
          add: "./README.md"
